Repository Magnet-js/schule, pull requests merged in 2025-08, with the labels that each got.

#11 ci: Create add-labels-to-pr.yml workflow
  .github/workflows/add-labels-to-pr.yml
Labels: enhancement, github-actions, awaiting-feedback

#8 chore: Fix .gitignore
  .gitignore
Labels: bug, chore

#14 feat: Implement api server
  backend/config/config.go
  backend/go.mod
  backend/go.sum
  backend/internal/api/routes.go
  backend/internal/api/server.go
  backend/main.go
  docker-compose.yml
  docs/backend/apiDocs.md
Labels: enhancement, backend, awaiting-feedback

#15 docs: Add forms
  docs/formulare/Meldung über eine Änderung der Schülerdaten.pdf
  docs/formulare/Stammdatenblatt.pdf
Labels: documentation

#23 chore: implement makefile
  Makefile
Labels: chore
